services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: "moneymesh"
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - '5435:5432'
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
